[project]
name = "weird"

[dependencies]
BH = "*"
DBI = "*"
DEoptimR = "*"
DepthProc = "*"
DiagrammeR = "*"
FNN = "*"
FastPCS = "*"
GGally = "*"
HMDHFDplus = "*"
KernSmooth = "*"
MASS = "*"
Matrix = "*"
MatrixModels = "*"
MortalityLaws = "*"
OutliersO3 = "*"
"R.cache" = "*"
"R.methodsS3" = "*"
"R.oo" = "*"
"R.utils" = "*"
R6 = "*"
RANN = "*"
RColorBrewer = "*"
RCurl = "*"
Rcpp = "*"
RcppArmadillo = "*"
RcppEigen = "*"
RcppEnsmallen = "*"
RcppProgress = "*"
RhpcBLASctl = "*"
S7 = "*"
SparseM = "*"
StMoMo = "*"
XML = "*"
abind = "*"
alphahull = "*"
anytime = "*"
aplpack = "*"
ash = "*"
askpass = "*"
backports = "*"
base64enc = "*"
bit = "*"
bit64 = "*"
bitops = "*"
blob = "*"
boot = "*"
brew = "*"
brio = "*"
broom = "*"
bslib = "*"
cachem = "*"
callr = "*"
cassowaryr = "*"
cellWise = "*"
cellranger = "*"
cli = "*"
clipr = "*"
cobs = "*"
codetools = "*"
collections = "*"
colorspace = "*"
commonmark = "*"
conflicted = "*"
cpp11 = "*"
crayon = "*"
crosstalk = "*"
crs = "*"
cubature = "*"
curl = "*"
"data.table" = "*"
dbplyr = "*"
dbscan = "*"
deldir = "*"
desc = "*"
digest = "*"
distributional = "*"
dobin = "*"
dotCall64 = "*"
downlit = "*"
dplyr = "*"
dtplyr = "*"
energy = "*"
english = "*"
evaluate = "*"
evd = "*"
fable = "*"
fabletools = "*"
fanplot = "*"
fansi = "*"
farver = "*"
fastmap = "*"
feasts = "*"
fields = "*"
fontawesome = "*"
forcats = "*"
forecast = "*"
fracdiff = "*"
fs = "*"
gargle = "*"
generics = "*"
geometry = "*"
geozoo = "*"
ggdendro = "*"
ggdist = "*"
ggforce = "*"
ggokabeito = "*"
ggplot2 = "*"
ggraph = "*"
ggrepel = "*"
ggstats = "*"
ggtime = "*"
gh = "*"
gifski = "*"
gitcreds = "*"
glue = "*"
gnm = "*"
googledrive = "*"
googlesheets4 = "*"
graphlayouts = "*"
gratia = "*"
gridExtra = "*"
gsl = "*"
gtable = "*"
haven = "*"
here = "*"
highr = "*"
hms = "*"
htmltools = "*"
htmlwidgets = "*"
httr = "*"
httr2 = "*"
ids = "*"
igraph = "*"
ini = "*"
interp = "*"
isoband = "*"
isotree = "*"
janitor = "*"
jquerylib = "*"
jsonlite = "*"
kableExtra = "*"
kernlab = "*"
knitr = "*"
ks = "*"
labeling = "*"
languageserver = "*"
later = "*"
latex2exp = "*"
lattice = "*"
lazyeval = "*"
leaderCluster = "*"
lifecycle = "*"
linprog = "*"
lintr = "*"
lmtest = "*"
lookout = "*"
lpSolve = "*"
lubridate = "*"
lvplot = "*"
magic = "*"
magrittr = "*"
maps = "*"
matrixStats = "*"
mclust = "*"
memisc = "*"
memoise = "*"
mgcv = "*"
mime = "*"
minerva = "*"
mirai = "*"
mlpack = "*"
modelr = "*"
multicool = "*"
mvnfast = "*"
mvtnorm = "*"
nanonext = "*"
nlme = "*"
nnet = "*"
np = "*"
numDeriv = "*"
openssl = "*"
otel = "*"
patchwork = "*"
pbapply = "*"
pcaPP = "*"
pillar = "*"
pkgbuild = "*"
pkgconfig = "*"
pkgload = "*"
plotly = "*"
plyr = "*"
polyclip = "*"
pracma = "*"
prettyunits = "*"
processx = "*"
progress = "*"
progressr = "*"
promises = "*"
ps = "*"
purrr = "*"
quadprog = "*"
quantreg = "*"
qvcalc = "*"
ragg = "*"
rappdirs = "*"
rdtools = "*"
readr = "*"
readxl = "*"
relimp = "*"
rematch = "*"
rematch2 = "*"
reprex = "*"
reshape2 = "*"
rex = "*"
rgl = "*"
rlang = "*"
rlist = "*"
rmarkdown = "*"
roahd = "*"
robustX = "*"
robustbase = "*"
rootSolve = "*"
roxygen2 = "*"
rprojroot = "*"
rrcov = "*"
rstudioapi = "*"
rvest = "*"
sass = "*"
scales = "*"
selectr = "*"
sgeostat = "*"
shape = "*"
slider = "*"
sm = "*"
snakecase = "*"
sp = "*"
spam = "*"
"spatstat.data" = "*"
"spatstat.geom" = "*"
"spatstat.random" = "*"
"spatstat.sparse" = "*"
"spatstat.univar" = "*"
"spatstat.utils" = "*"
splancs = "*"
statmod = "*"
stbl = "*"
stray = "*"
stringi = "*"
stringr = "*"
styler = "*"
survival = "*"
svd = "*"
svglite = "*"
sys = "*"
systemfonts = "*"
tensor = "*"
textshaping = "*"
tibble = "*"
tidygraph = "*"
tidyr = "*"
tidyselect = "*"
tidytuesdayR = "*"
tidyverse = "*"
timeDate = "*"
timechange = "*"
tinytex = "*"
tourr = "*"
tsibble = "*"
tsibbledata = "*"
tweedie = "*"
tweenr = "*"
tzdb = "*"
urca = "*"
utf8 = "*"
uuid = "*"
vctrs = "*"
viridis = "*"
viridisLite = "*"
visNetwork = "*"
vital = "*"
vroom = "*"
warp = "*"
withr = "*"
xfun = "*"
xml2 = "*"
xmlparsedata = "*"
yaml = "*"
zoo = "*"

[dependencies.weird]
git = "robjhyndman/weird"
